USER_STATUS_INACTIVE = 'INACTIVE'
USER_STATUS_ACTIVE = 'ACTIVE'
USER_STATUS_LOCKED = 'LOCKED'

TENANT_STATUS_ACTIVE = 'ACTIVE'
TENANT_STATUS_MOVED_OUT = 'MOVED_OUT'

USER_ROLE_SUPER_ADMIN = 'SUPER_ADMIN'
USER_ROLE_ADMIN = 'ADMIN'
USER_ROLE_SITE_MANAGER = 'SITE_MANAGER'
USER_ROLE_USER = 'USER'

CONF_KEY_SENDER_EMAIL_ADDRESS = 'SENDER_EMAIL_ADDRESS'
CONF_KEY_SENDER_EMAIL_PASSWORD = 'SENDER_EMAIL_PASSWORD'
CONF_KEY_SSL_PORT = 'SSL_PORT'
CONF_KEY_SMTP_SERVER = 'SMTP_SERVER'
CONF_KEY_SCORE_ALERT_LEVEL_LOW = 'SCORE_ALERT_LEVEL_LOW'
CONF_KEY_SCORE_ALERT_LEVEL_MEDIUM = 'SCORE_ALERT_LEVEL_MEDIUM'
CONF_KEY_SCORE_ALERT_LEVEL_HIGH = 'SCORE_ALERT_LEVEL_HIGH'
CONF_KEY_SCORE_ALERT_THRESHOLD = 'SCORE_ALERT_THRESHOLD'
CONF_KEY_ACTIVITY_TRACKING_WINDOW = 'ACTIVITY_TRACKING_WINDOW'

DEFAULT_SCORE_ALERT_LEVEL_LOW = 0
DEFAULT_SCORE_ALERT_LEVEL_MEDIUM = 5
DEFAULT_SCORE_ALERT_LEVEL_HIGH = 10
DEFAULT_SCORE_ALERT_THRESHOLD = 15
DEFAULT_ACTIVITY_TRACKING_WINDOW = 7

ALERT_LEVEL_HIGH = 'HIGH'
ALERT_LEVEL_MEDIUM = 'MEDIUM'
ALERT_LEVEL_LOW = 'LOW'


CANADA_PROVINCE_LIST = [
    {'code':'NL', 'name': 'Newfoundland and Labrador'},
    {'code':'PE', 'name': 'Prince Edward Island'},
    {'code':'NS', 'name': 'Nova Scotia'},
    {'code':'NB', 'name': 'New Brunswick'},
    {'code':'QC', 'name': 'Quebec'},
    {'code':'ON', 'name': 'Ontario'},
    {'code':'MB', 'name': 'Manitoba'},
    {'code':'SK', 'name': 'Saskatchewan'},
    {'code':'AB', 'name': 'Alberta'},
    {'code':'BC', 'name': 'British Columbia'},
    {'code':'YT', 'name': 'Yukon'},
    {'code':'NT', 'name': 'Northwest Territories'},
    {'code':'NU', 'name': 'Nunavut'}
]